<a href="https://colab.research.google.com/github/adityagit386-hub/Amazon-Prime-Video-Analysis-dashboard/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
numbers= np.array([1,2,3,4,5,6,7,8,9,10])

In [ ]:
arr= np.where(numbers>5, numbers*3,numbers)
print(arr)

[ 1  2  3  4  5 18 21 24 27 30]


adding and removing


In [ ]:
arr1= np.array([1,2,3])
arr2 = np.array([4,5,6])
conbined= np.concatenate((arr1, arr2))
print(conbined)

[1 2 3 4 5 6]


In [ ]:
arr3=np.array([7,8,9])
print(arr1.shape == arr2.shape)

True


In [ ]:
arr4=np.array([[1,2],[3,4]])
new_row= np.array([[5,6]])
arr5= np.vstack((arr4,new_row))
print(arr5)

new_column= np.array([[7],[8]])
arr6= np.hstack((arr4,new_column))
print(arr6 )


[[1 2]
 [3 4]
 [5 6]]
[[1 2 7]
 [3 4 8]]


In [3]:
import matplotlib.pyplot as plt


In [5]:
import numpy as np

sales_data = np.array([
    [1, 150000, 180000, 220000, 250000],  # Paradise Biryani
    [2, 120000, 140000, 160000, 190000],  # Beijing Bites
    [3, 200000, 230000, 260000, 300000],  # Pizza Hub
    [4, 180000, 210000, 240000, 270000],  # Burger Point
    [5, 160000, 185000, 205000, 230000]   # Chai Point
])

print("==== Zomato sales analysis ==== ")
print("\n Sales data shape", sales_data.shape)
print("\n Sample data for 1st 3 restau: ", sales_data[:3])

==== Zomato sales analysis ==== 

 Sales data shape (5, 5)

 Sample data for 1st 3 restau:  [[     1 150000 180000 220000 250000]
 [     2 120000 140000 160000 190000]
 [     3 200000 230000 260000 300000]]


In [12]:
print(np.sum(sales_data, axis=0) )
print("\nyearly Total",np.sum(sales_data[:,1:], axis=1) )

[     15  810000  945000 1085000 1240000]

yearly Total [800000 610000 990000 900000 780000]


In [25]:
print(np.min(sales_data[:, 1:], axis=0))

avg= np.mean(sales_data[:,1:], axis =1)
print(avg )

[120000 140000 160000 190000]
[200000. 152500. 247500. 225000. 195000.]


In [38]:
cumsum= np.cumsum(sales_data[:,1:],axis =1)
print(cumsum)



[[150000 330000 550000 800000]
 [120000 260000 420000 610000]
 [200000 430000 690000 990000]
 [180000 390000 630000 900000]
 [160000 345000 550000 780000]]
